frontend:
    port: 8000

api:
  endpoints:
    - path: "*"
      name: api-gateway
      method: "GET"
      url: localhost
      port: 9000
      location: http://${api.endpoints[0].url}:${api.endpoints[0].port}

    - path: "*"
      name: frontend
      method: "GET"
      url: localhost
      port: 8000
      location: http://${api.endpoints[0].url}:${api.endpoints[0].port}
      username: ""
      password: ""

    - path: "[/]*api/files.*"
      name: files
      method: "GET"
      url: localhost
      port: 7000
      location: http://${api.endpoints[1].url}:${api.endpoints[1].port}
      username: ""
      password: ""

    - path: "[/]*api/minio.*"
      name: minio
      method: "GET"
      url: localhost
      port: 8500
      location: http://${api.endpoints[2].url}:${api.endpoints[2].port}
      username: "test1234"
      password: "test1234"

    - path: "[/]*api/backend.*"
      name: backend
      method: "GET"
      url: localhost
      port: 5000
      location: http://${api.endpoints[3].url}:${api.endpoints[3].port}
      username: "test1234"
      password: "test1234"